### ISSUE TITLE
tlog : change prev hash value of the first aggregation

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#104]
It currently use privKey which is not secure.

https://github.com/g8os/blockstor/blob/46a8fbc7b913a649b73e205c5779235b8c8b2430/tlog/tlogserver/flusher.go#L143-L147

There were no strong reason to use privKey, it only bassed on unfinished discussion on the tlog telegram group

**Comment by GlenDC** [comment]
I see 2 possible solutions for this issue:

+ either we have simply a unique 'genesis' hash (constant), which value we use for `prevHash` value of the first aggregation;
+ or we have an actual 'genesis' aggregation (constant), which is defined for all chains as the first aggregation, and we take the hash of that aggregation as the `prevhash` value of the first (real) aggregation. The `prevhash` of the 'genesis' aggregation would be the hash of itself;

**Comment by iwanbk** [comment]
I prefer first solution, because I can't see the advantage of the 2nd other than it give us additional unnecessary work.

**Comment by GlenDC** [comment]
I agree.

**Comment by iwanbk** [comment]
how about 32 bytes of zero?

**Comment by GlenDC** [comment]
> how about 32 bytes of zero?

I think that's an acceptable first hash
