### ISSUE TITLE
tlog : send notification when flush by timeout happens

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#105]
previously on https://github.com/g8os/tlog/issues/33

**Comment by iwanbk** [comment]
also fixed by #127

**Comment by GlenDC** [comment]
> also fixed by #127

Can you link me to the code where this happens @iwanbk, I don't seem to find what you mean.

**Comment by iwanbk** [comment]
https://github.com/g8os/blockstor/blob/develop/tlog/tlogserver/server/flusher.go#L131-L155
