### ISSUE TITLE
tlog : redis pool package

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#112]
Previously we want to use same package as nbdserver but found out that it is not a good idea.
see #92

**Comment by GlenDC** [comment]
@iwanbk what would you like to see done for this issue?

**Comment by GlenDC** [comment]
closed via cad8330

**Comment by iwanbk** [comment]
```
@iwanbk what would you like to see done for this issue?
```
i don't have clear requirement about this yet.
The only thing i know is that the ardb server used by tlog will be slower than the one used by nbdserver.

I think your implementation is enough now, we can improve it later. Thanks!

Maybe @grimpy or @robvanmieghem can give more details about ardb setup for tlog.
