### ISSUE TITLE
tlog capnp optimization 

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#117]
Part of #40 
from the profiling i attached below, majority of the time is on `encodeCapnp` func.

[tlog.pdf](https://github.com/g8os/blockstor/files/978372/tlog.pdf)

**Comment by iwanbk** [comment]
I tried few different  ways to encode the aggregation, all resulted in similar time, no significant improvement.

(1) we are storing  tlog blocks capnp object in memory. 

Instead of calling `List.Set` directly, i get the block object and copy each fields.

the code is like this
```go
block := blockList.At(i)
copyBlock(&block, storedBlocks[i])
```
profiling data : 
[tlog-capnp-set.pdf](https://github.com/g8os/blockstor/files/978477/tlog-capnp-set.pdf)

(2) instead of storing tlog block object, i store the raw packet, and add one field to TlogAggregation:
```
packets @6 :List(Data); # list of raw packets
```
when building the aggregation
```
 packetList.Set(i, storedBlocks[i])
```

profiling data: 
[tlog-raw.pdf](https://github.com/g8os/blockstor/files/978485/tlog-raw.pdf)

(3) when encoding the capnp, we currently use `buf:=new(bytes.Buffer)` to allocate the buffer.
I changed it to `buf := bytes.NewBuffer(preallocatedByteSlice)`

profiling data : 
[tlog-raw-newbuffer.pdf](https://github.com/g8os/blockstor/files/978488/tlog-raw-newbuffer.pdf)

I'm going to think more about (2), it seems promising.

**Comment by iwanbk** [comment]
from the profiling data, GC work hard on (2) and (3), it seems that the GC work very hard.
I managed to make it 2x faster by assign the storedBlocks to nil after it's usage.

The code become like this
```go
func (f *flusher) encodeCapnp(vdiskID string, blocks [][]byte, lastHash []byte) ([]byte, error) {
    // create capnp aggregation
    msg, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))
    if err != nil {
        return nil, err
    }
    agg, err := schema.NewRootTlogAggregation(seg)
    if err != nil {
        return nil, err
    }

    agg.SetName("The Go Tlog")
    agg.SetSize(uint64(len(blocks)))
    agg.SetTimestamp(uint64(time.Now().UnixNano()))
    agg.SetPrev(lastHash)
    agg.SetVdiskID(vdiskID)

    packetList, err := agg.NewPackets(int32(len(blocks)))
    if err != nil {
        return nil, err
    }
    estimatedLen := 500
    for i := 0; i < packetList.Len(); i++ {
        packetList.Set(i, blocks[i])
        estimatedLen += len(blocks[i])
    }

    /*blockList, err := agg.NewBlocks(int32(len(blocks)))
    */

    data := make([]byte, estimatedLen)
    //buf := new(bytes.Buffer)
    buf := bytes.NewBuffer(data)

    err = capnp.NewEncoder(buf).Encode(msg)
    for i := 0; i < len(blocks); i++ {
        blocks[i] = nil
    }
    return buf.Bytes()[:], err
}
```

repeating above comment, 
```
packets @6 :List(Data); # list of raw packets
```
So, the aggregation store raw tlog message instead of raw tlog objects

let me know if it is a bad idea to store the raw message. especially if rivine/blockchain stuffs need it to be stored as tlog object. @robvanmieghem ?

We won't have decoding problem with it.

**Comment by GlenDC** [comment]
As far as I know, the data will be stored in the rivine blockchain as binary data anyhow, without really knowing about its content, so I don't think that's going to be an issue for rivine.

**Comment by iwanbk** [comment]
```
I managed to make it 2x faster by assign the storedBlocks to nil after it's usage.
```
unfortunately i can't reproduce the improvement anymore, maybe i was dreaming, but...

Then i moved to use redis instead of ardb,  result:
- current code only got very minor improvement
- the improvement above got almost 4x speedup (from 24 seconds down to 7 seconds)

I can only think that it is because the slowness of my HDD.

work in progress can be found at `tlog-raw-block` branch.

**Comment by iwanbk** [comment]
I tested (1) again and it got a bit better improvement than (2) and (3).
So, i decided to use (1) for now instead of (2) and (3) because storing block as TlogBlock type is cleaner than storing it as raw byte.

**Comment by iwanbk** [comment]
i keep `tlog-raw-block` branch in case we need it later.

**Comment by iwanbk** [comment]
I use a bigger file to test and the result still consistent with previous test with smaller file.

**Comment by iwanbk** [comment]
reopen this issue because of test result at https://github.com/g8os/blockstor/issues/128#issuecomment-300112338

**Comment by robvanmieghem** [comment]
It stuns me to see your first profiling graph

**Comment by iwanbk** [comment]
latest profiling graph,
[tlog-log-async.pdf](https://github.com/g8os/blockstor/files/986241/tlog-log-async.pdf)

i use pdf here instead of .png because IMO the .pdf is better, easier to read.

**Comment by iwanbk** [comment]
I tested again the (2) and (3) solutions, no improvement.
I think we need to do these things:
- create bencmark test for the capnp encoding
- look at zombiezen/go-capnproto2 internal

**Comment by GlenDC** [comment]
> look at zombiezen/go-capnproto2 internal

I agree, both linked profile graphs seem to indicate that if we can get a significant speed improvement within the `zombiezen/go-capnproto2 internal` code, that we'll benefit a lot from it. Capnp might be fast to transfer over the wire, but it seems to be pretty slow at the moment off the wire :(

**Comment by iwanbk** [comment]
other than capnp encoding, the other part which eat CPU is the GC.
I suspect that it also caused by the capnp encoding.

**Comment by GlenDC** [comment]
Yeah you are right, I'm going to dive in the capnp go code and see how we can make it faster, as it would help us a lot.

**Comment by iwanbk** [comment]
I got big improvement by modifying this line.

```go
sg, seg, err := capnp.NewMessage(capnp.SingleSegment(nil)) 
```
to 
```go
sg, seg, err := capnp.NewMessage(capnp.SingleSegment(somePreAllocatedBuf)) 
```
Actually i thought i already did this optimization because this is the optimization i already found in `gotest` https://docs.greenitglobe.com/ibk/gotests/src/mmap_capnp/mmap_capnp/common.go#L15

Using same data as this benchmark https://github.com/g8os/blockstor/issues/128#issuecomment-300109155.

Now it only took : 13.7 seconds.
comparing to other test:
- current code : 18 seconds
- no capnp encoding, only blocks append : 12 seconds
- tlog simply ignore the message : 11 seconds

profiling data : 
[tlog-capnp-buf.pdf](https://github.com/g8os/blockstor/files/988680/tlog-capnp-buf.pdf)

work in progress can be found at `tlog-capnp-improvement` branch

**Comment by iwanbk** [comment]
did the similar things to the client, gave me 0.7 seconds improvement, from 13.7 second to 13 seconds.

nbd profiling data before : 
[nbd-capnp-no-buf.pdf](https://github.com/g8os/blockstor/files/989013/nbd-capnp-no-buf.pdf)

nbd profiling data after : 
[nbd-capnp-buf.pdf](https://github.com/g8os/blockstor/files/989014/nbd-capnp-buf.pdf)

**Comment by iwanbk** [comment]
Did the same thing with tlog response, it only took 12.6 seconds, from 18 seconds :).

implemented at #133

**Comment by iwanbk** [comment]
Remove my assignment, @GlenDC you can continue my work if you want, as we discussed in telegram.
If you do, please set the assigment to you. So we know that you work on this.

I didn't take a deep look at the go-capnproto2 because it doesnt look big in profiling graph anymore.

**Comment by iwanbk** [comment]
latest benchmark:
- without tlog : 5.8 s
- tlog without store : 9.6 seconds
- full tlog : 12.6 seconds

**Comment by iwanbk** [comment]
@GlenDC feel free to reopen if you want to work on it again.
