### ISSUE TITLE
integrate yaml config into tlogreplay tool

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#119]
Master has to be merged into develop, and the yaml config has to be used in the tlogreplay tool as well, as we no longer make use of the gridapi within blockstor.

**Comment by GlenDC** [comment]
Best to only do this, once @grimpy is happy with the new way of working within blockstor. He can probably confirm this in a couple of days time.

**Comment by iwanbk** [comment]
Is it mean the tlogreplay wont need to store gridapiservser anymore?

**Comment by GlenDC** [comment]
> Is it mean the tlogreplay wont need to start gridapiservser anymore?

It means that:

+ the CLI Flags [gridapiaddress , nonDedupedExports and testArdbConnectionStrings ](https://github.com/g8os/blockstor/blob/640d27d4cba573aab589db1fa4e94cd602be0767/cmd/tlogreplay/main.go#L21-L23) are no longer needed, and instead we need to add a configPath string flag.
+ The optional [gridapi stub](https://github.com/g8os/blockstor/blob/640d27d4cba573aab589db1fa4e94cd602be0767/cmd/tlogreplay/main.go#L43-L55) isn't required either anymore, as no information is ever fetched from the gridapi.
+ [`storagecluster.NewClusterClientFactory`](https://github.com/g8os/blockstor/blob/640d27d4cba573aab589db1fa4e94cd602be0767/cmd/tlogreplay/main.go#L63) takes now the configPath as paramater, instead of the gridapiaddress;
+ ... same for the [ardb.BackendFactoryConfig](https://github.com/g8os/blockstor/blob/640d27d4cba573aab589db1fa4e94cd602be0767/cmd/tlogreplay/main.go#L69-L74).

**Comment by GlenDC** [comment]
But for now, I wouldn't botter with changing that, as it might be that @grimpy and/or others don't like the new approach either, and we might have to go back to the design board. And it doesn't impact any of the design of the tlog module and tlogreplay cli util anyhow, so no reason to merge it already into the develop branch.

**Comment by GlenDC** [comment]
Closed by 38de082
