### ISSUE TITLE
tlog server : add support for unordered & duplicated message

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#143]
we need it to support multiple connections per vdisk

Some thought from #128 
```
 i can see two alternatives:

use slice like now, but we sorted the slice.
use 3rd party data structure : https://github.com/emirpasic/gods, https://github.com/Workiva/go-datastructures, etc....
```

**Comment by iwanbk** [comment]
Changes needed:
- before flushing, make sure we have all sequences needed.
- keep note about latest sequence flushed. To avoid processing flushed sequence
- It might be easier to use data structure that ordered automatically. (e.g. ordered by key)

**Comment by iwanbk** [comment]
A work in progress can be found on `tlog-unordered-msg` branch.
It implemented according to the above comment.
A unit test has been added with unordered and duplicated scenario.

In my test with all messages being ordered, this branch was faster than the master branch. I can only think that it is because we have more buffer in the server due to one more goroutine to process the messages.
Current vdisk goroutines:
- the old goroutine which flush the aggregations
- new goroutines that buffer the incoming messages and supply the ordered messages to first goroutine

test result:
- without tlog : 5.8 seconds
- this branch : 9.9 seconds
- master branch : 11.8 seconds

**Comment by iwanbk** [comment]
> It might be easier to use data structure that ordered automatically. (e.g. ordered by key)

The  package chosen is https://godoc.org/github.com/emirpasic/gods/sets/treeset with these consideration:
- it is ordered
- it is a 'set', will handle duplicated message ( we can easily add logic to prevent it though)

 there is no strong reason to use this package yet, there are actually many packages out there and we need to benchmark them to get the best packages. And i think it should be done in different issue/task

**Comment by GlenDC** [comment]
> it is a 'set', will handle duplicated message ( we can easily add logic to prevent it though)

I don't think we require this, as we can really simply handle this while we check if we have the expectedIndex available:

```
handleAndSend if index == expectedIndex
discardAndLog else-if index < expectedIndex
```

> there is no strong reason to use this package yet, there are actually many packages out there and we need to benchmark them to get the best package. And i think it should be done in different issue/task

I agree, for now though it shouldn't block this issue, as that's more an optimization.

**Comment by GlenDC** [comment]
Thinking about it, it might not be too bad to use a set, to remove duplicates, as it shouldn't be that expensive. I put it together in the new issue #164.

**Comment by iwanbk** [comment]
```
I don't think we require this, as we can really simply handle this while we check if we have the expectedIndex available:

handleAndSend if index == expectedIndex
discardAndLog else-if index < expectedIndex
```
yep, already in the PR.

But note that duplicated message can also happens when the `sequence > expectedSequence`, and we need to chose best data structure to handle this.
