### ISSUE TITLE
Handle 'empty' blocks

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#15]
Purpose: ability to `dd` a raw file in to the nbdserver to create base volumes.
When writing a block full of `0`'s, we should not create new lba structures for it (even though existing ones should be overwritten off course).
A solution might be to execute a `delete` of a completely empty lba-shard.

**Comment by GlenDC** [comment]
While resolving this issue I'll also:

+ Make sure we only pad 0's on left side, not the right side;
+ Measure the distribution between the 4 options in `WriteAt`, and rearrange them from most common to least common;
