### ISSUE TITLE
add automated test for the tlog replay logic

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#157]
as part of #86

**Comment by GlenDC** [comment]
This test should do the following things in order:

1. Start a tlogserver;
2. Start an NBDServer Backend with tlogclient integration;
3. Generate 16 MiB of random data (with some partial and full zero blocks) and write it to the nbd backend;
4. Validate that all the data is retrievable and correct;
5. Wipe all data on the arbd;
6. Validate that the data is no longer retrievable via the backend;
7. Replay the tlog aggregations (this is the part that should test the logic of the tlogreplay tool which is integrated in the g8stor tool suite);
8. Validate that all the data is _again_ retrievable and correct;

**Comment by iwanbk** [comment]
Sounds good

**Comment by GlenDC** [comment]
Pushed my current WIP version of the test described above @ https://github.com/g8os/blockstor/commit/7d50e16cc1434cf2f8584de87be1db694b1fee3d#diff-ba74794d0e3e68c838589226c9f1303d

Feel free to take a look at it @iwanbk, because for now it seems to fail the test for both vdisk types. The code is pushed on a branch, so you can also check it out. If you can't find it, don't worry, I'll continue to work on this tomorrow.

The bug is either in my test code, or the failure indicates an actual bug in the tlog code.

The data at step (8) is no longer all-zeroes, so there is definitely data replayed, but it's not the correct data :(

If you can't find it, I might first resolve https://github.com/g8os/blockstor/issues/178 tomorrow, before continuing this, as I think it will help a lot in my stability.

**Comment by iwanbk** [comment]
I did a simple test:
- format an nbd device, mount it, and wrote some file
- destroy the nbd data storage
- make sure nbd device can't be mounted
- restore it
- make sure nbd device can be mounted and check the written file

it works

> If you can't find it, I might first resolve #178 tomorrow, before continuing this, as I think it will help a lot in my stability.

yep, agree
