### ISSUE TITLE
re-send the tlog if doesn't get response or response says error

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#162]
Part of #126

**Comment by iwanbk** [comment]
implementation design:
- keep the transaction log in buffer/cache until it received by tlog server
- capnp encoding wont be retried except that it is caused by system (e.g. memory)  error
- if timeout passed, we re send the tlog message.
- the number of retry we will do should be configurable

**Comment by iwanbk** [comment]
A work in progress can be found on `tlogclient-retry-timeout` branch.

I added a container to manage the block that already sent but not get OK response yet.
I'm happy with the API but i think it still need to be improved:
- unit test (still no idea how to simulate this case)
- it still use Go map, which is work but might be slow for this case. i think i can repace it with https://godoc.org/github.com/emirpasic/gods/maps/treemap to improve the performance

**Comment by iwanbk** [comment]
> it still use Go map, which is work but might be slow for this case. i think i can repace it with https://godoc.org/github.com/emirpasic/gods/maps/treemap to improve the performance

treemap is not good choice, because it order the data by it's key.
What we need is something that other the data by it's content and we can still access it by key.

If we can't find it, we can use two data structure to avoid iterating over unordered map.
But using two data structures itself add some kind of complexity to the code and might create maintenance issue.

Fortunately, we don't need it now because from my benchmark, it doesn't give perfomance reduction to the client.

**Comment by iwanbk** [comment]
> unit test (still no idea how to simulate this case)

Implementation at PR #181 still doesn't have unit test, i only tested it manually there.

We might need fake/dummy tlog server to properly test it automatically.

**Comment by GlenDC** [comment]
I think it should be pretty do-able to write a test for this. Could you describe to me:

+ what are the scenarios that you want to test;
+ what are you exactly doing to manually test it for now;

Knowing this I might be able to help you with this.

**Comment by iwanbk** [comment]
Considered this issue and the test as low priority, was planning to do it after i feel safe we can finish other issue in this milestone ( which i don't think so).
I'm going to check all other issues after finishing #183

> what are you exactly doing to manually test it for now;

modified the 'Recv':
- for some sequences, i ignored the response (it simulates timeout)
- for some sequences, i force it to enter `if tlog.BlockStatusRecvFailed` condition

what is your plan to simulate the server btw?

**Comment by GlenDC** [comment]
Not sure, all depends on what we want to tests etc.

**Comment by iwanbk** [comment]
I think we can create something that implement io.Reader and io.Writer to act as dummy tlog server.

After checking other issues, i think can work on it tomorrow.

**Comment by iwanbk** [comment]
a work in progress can be found on `test-resend` branch.
It currently passed the travis build but actually it has race condition, checking it now.

**Comment by iwanbk** [comment]
fixed by using `io.Pipe` instead of tricky `bytes.Buffer` to simulate the tcp connection.

**Comment by GlenDC** [comment]
> It currently passed the travis build but actually it has race condition, checking it now.

There still seems to be a race condition, or similar reason why the test-resend test fails, as it failed once at travis for my PR #194, but restarting the job made it pass.

**Comment by GlenDC** [comment]
Can't really reproduce it, seems like you need to have a high workload relative to your CPU power to make it trigger, and even then travis only triggered it once:

Here is the snippet that made it fail that one time:

```
t=2017-05-23T16:35:32+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:32+0000 lvl=info msg="connection from 127.0.0.1:45814 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:32+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:32+0000 lvl=info msg="connection from 127.0.0.1:45828 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45830 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45900 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45902 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45904 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45906 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45908 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45910 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45912 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45914 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45916 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45918 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45920 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45922 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45924 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45926 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45928 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45930 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45932 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45934 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45936 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45938 dropped: EOF" module=global caller=server.go:103
t=2017-05-23T16:35:37+0000 lvl=eror msg="failed to decode tlog: EOF" module=global caller=server.go:215
t=2017-05-23T16:35:37+0000 lvl=info msg="connection from 127.0.0.1:45940 dropped: EOF" module=global caller=server.go:103
--- FAIL: TestSimpleReconnect (5.03s)
	Error Trace:	reconnect_test.go:56
	Error:      	Not equal: 
	            	expected: 0x1
	            	received: 0x0
```

Note sure if it is related to the race condition you had, but posting it here for now.

All tests in PR #194 pass though, seemed to only have failed once. Retrying it fixed it immediately.

**Comment by iwanbk** [comment]
```
Error Trace:	reconnect_test.go:56
	Error:      	Not equal: 
	            	expected: 0x1
	            	received: 0x0
```

> Note sure if it is related to the race condition you had, but posting it here for now.

No, the race condition i had was in resend_test.go, while this issue is in reconnect_test

**Comment by iwanbk** [comment]
> Ah ok, well I couldn't reproduce it, let's see if it comes back.

It happens right now, in master branch

**Comment by GlenDC** [comment]
yeah it must be a race condition somewhere. Question will be if it also affects production code, or it is simply because of the difference in test code and production code and how functions and logic get differently used.

**Comment by GlenDC** [comment]
Or it could also be that due to some bug, the sequence number resets in certain chaotic scenarios.
