### ISSUE TITLE
Add g8stor list 

### ISSUE THREAD

**Issue by khaledkbadr** [g8os/blockstor#173]
It'd be nice if `g8stor`  has a list feature to list vdisks

**Comment by GlenDC** [comment]
@khaledkbadr I suppose you mean the ones available in [the config file](https://github.com/g8os/blockstor/blob/master/docs/nbd/config.md)? Or do you suggest another place where we can get this information from?

**Comment by khaledkbadr** [comment]
I think to be consistent with the existing commands to be from the ardb for example `g8stor list localhost:16379`

**Comment by GlenDC** [comment]
I don't really see how that would be done. There is no list of vdisks available on a connection, they are basically just identified by their `vdiskID`, which could be any kind of value. Also going through all values is really pretty slow, and should definitely not be done in production.

In combination with the config file, it is something we could do. As we could check which vdisks are linked to that storage. Except for the fact that we have both dataStorage and metadataStorage, thus which would would we be interested in.

But when limiting it to a config file, the result will be very limited, and not very useful. But without that, I think we would really need some kind of source, could be an RPC service, but at the moment I don't think there is a "good" way to really check which vdisks are present on a vdisk.

While at the moment there is no "good" way to get a list of vdisks, we could perhaps work on storing a `set` of vdisks on the metadataStorage, such that for purposes like this we can simply consult that `set`. But in that case we would need to do some work in the `nbdserver` module as well.

**Comment by robvanmieghem** [comment]
It's possible to list by searching through the keys

**Comment by GlenDC** [comment]
> It's possible to list by searching through the keys

Sure, but that's very slow, and they even warn to not use this in production. On top of that how would you be sure that it's a vdisk?

Or can we assume that all our data on an `ardb` is only ever `vdisk` info?

**Comment by robvanmieghem** [comment]
good point and indeed, it would be very slow. This is actually the reason @grimpy wanted to seperate the metadata db from the normal one. We might add this option with a big fat warning and only execute it passed -force or something so people don't start using it by accident.

**Comment by GlenDC** [comment]
Ok, that sounds fair enough for now. Although I think if we want to do this based on the ardb connection alone, it would be better to store a `set` though (this set would have to be maintained in all tools that would interact with these ardbs of course, so that would be the `g8stor` tool suite, and `nbdserver` for now). Doesn't sounds like it would give any overhead if done well, and we could much safer get this information.

Also @robvanmieghem can you assign a milestone to this, so I know how to prioritize this issue.

**Comment by robvanmieghem** [comment]
Let me think about it, going to bed now :-), assigning it to me for now

**Comment by grimpy** [comment]
@GlenDC mainting such a set might become a cumbersome task todo. If an ardb is used for metadata alone you could simply list all keys if its mixed data/metadata you could list all hsets and yes this would be slow but doable nevertheless. 

One of the possiblities for this features could be for maintaining our maser ardb which contains the templates.
This could potentially also be used in the future for openvcloud to automaticly sync existing templates in our model.
