### ISSUE TITLE
tlogclient can't finish work at end of nbdserver's backend life cycle

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#178]
At the moment, the nbdserver does not wait for the Backend's background routine (where we allow the tlogclient to do its work) to be finished. This is a problem, as it means that the tlog sent is corrupt.

On the tlogserver this event results in a log similar to the following:

```
EROR[05-18|16:26:00] failed to decode tlog: EOF               module=global caller=server.go:211
INFO[05-18|16:26:21] failed to send resp to :myvdisk, err:writev tcp 127.0.0.1:11211->127.0.0.1:62669: use of closed network connection module=global caller=server.go:235
^C
```

The solution will be to make the nbdserver _safely_ wait for the goroutine to be finished (a timeout value is to be used though, to prevent getting stuck due to a broken backend).

**Comment by iwanbk** [comment]
I believe it is the same/similar issue as #153

**Comment by GlenDC** [comment]
> I believe it is the same/similar issue as #153 

Oh really? The titel `only Flush the operation after it get Flushed by tlog` is a bit conflusing, what did you mean with that? Or did you mean exactly the same as what I'm here describing?

**Comment by iwanbk** [comment]
Nbdserver give all write operations a counter/sequence number and then send it to tlog server.

Then tlog server store and flush it.
I think nbdserver backend can only flush those write operations only after tlog flushed it.

**Comment by GlenDC** [comment]
Ah yeah, similar issues than, but not entirely the same. However I think then the solution for #153 as you describe it might also resolve this issue. Will take a look at it after I finished with PR #179 and Issue #157.

**Comment by iwanbk** [comment]
How is our progress on this issue?

**Comment by GlenDC** [comment]
Well as I said before, for me this issue is completely interlinked with #153, so as soon as a decent solution for that is found, this would be resolved as well.
