### ISSUE TITLE
provide tlog README documentation

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#180]
Currently the tlog readme documentation is still very minimal. It would be good to add information on how to use it, a bit of general information and how to integrate stuff like the client.

**Comment by robvanmieghem** [comment]
Some high level documentation on the what is included in the tlogaggregration structure and how they link together would also be an added value.
+ a small explanation on the flushing strategy

**Comment by iwanbk** [comment]
Blocked by #183

**Comment by iwanbk** [comment]
Added some docs to https://github.com/g8os/blockstor/blob/tlog-readme/tlog/readme.md and the linked docs mentioned there.
