### ISSUE TITLE
tlog : add redundancy to the metadata

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#183]
We already have redundancy mechanism for the data pieces using erasure encoding.

But we don't have it for the metadata (it currently only last hash).

My idea right now is using redis stored procedure to replicate the metadata to all storages we have.
So, we don't need the dedicated storage for metadata now, we can put it in the data&encoding storage.

What do you think @GlenDC @maxux @nbabenko?

**Comment by iwanbk** [comment]
@robvanmieghem

**Comment by GlenDC** [comment]
Sounds like something we can definitely try out. The metadata information is definitely important enough!

**Comment by robvanmieghem** [comment]
@iwanbk I was thinking about the same problem yesterday and how to solve that and came to more or less the same solution, spreading it over the k+m ardb's.

**Comment by robvanmieghem** [comment]
Moving this to an earlier milestone since this will impact the deployment from ays (a k+m storagecluster instead of a k+m+1)

**Comment by iwanbk** [comment]
> can't we use that same connection to update the metadata after writing the datashard? This would parallelise it as well.

Was thinking the same.

**Comment by iwanbk** [comment]
changes needed:
- use redis pipelining to write data and update last_hash
- update tlog decoder to check last hash from all storages.

**Comment by iwanbk** [comment]
a work in progress can be found on `tlog-metadata-redundancy` branch.
It implement mentioned changes from previous comment, plus removing metadata connection from tlogpool.

I'm quite happy with the implementation, only need to do final check before make it a PR.
