### ISSUE TITLE
Speed up reading

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#31]
Currently the reading spawns concurrent go routines and waits until they are all done. If more than the number of ardb connection is being read, this becomes really apparent since a lot of data is already present while not being written to the nbd client. We should already start writing data to the client from the moment the next block is available.

Tasks:
- [x] integrate latest changes into g8os/gonbdserver;
- [x] speed up reading;

**Comment by robvanmieghem** [comment]
This should actually be an issue in g8os/gonbdserver but the changes of  39a4f189ccf3430c1dea047058c1c70094798b01 should also be included then.

**Comment by GlenDC** [comment]
@robvanmieghem is it legal than to reply multiple times as an NBDServer for a single request?  as the reason it has to wait for now, is because we need to read all data before we can reply. In case nbd protocol supports this, I guess we could immediately start sending replies, and thus sending multiple replies for a _single_  READ request.

**Comment by robvanmieghem** [comment]
@GlenDC Why would that be necessary?

Assume bytes read is correct, the thing gives an io error any way if that is not the case.
And why can't the first block be already written to the client if the rest is still being fetched?

**Comment by robvanmieghem** [comment]
A second thing is that reading from lba shards that are in memory are blocked by fetching unknown lba shards. Suggest we do some profiling to see if that is the case.

**Comment by GlenDC** [comment]
It's true, for now the entire LBA thing is pretty blocking. I'll make an issue for it, and also take a look at it.

I thought it would be required as a reply consists out of the header, and than all the data. I guess as long as we only handle 1 request at a time, we could start sending data immediately, but that does make it impossible to handle multiple requests at the same time (not that we are doing that for now). Unless I am missing something.

**Comment by GlenDC** [comment]
Created issue #32 for it.

**Comment by GlenDC** [comment]
gonbdserver updated in master, integrating proposed changes:
https://github.com/g8os/gonbdserver/commit/6cee66e32be36e7c691dec79e5242ad4dc38f358

**Comment by GlenDC** [comment]
Finishing this issue later today. You can expect a PR completing this issue within the next 4-5 hours.

**Comment by GlenDC** [comment]
Also fixed your TODO related to FUA being only called the last Read/Write. Depending on the time I'll also fix some other TODO's along the way.
