### ISSUE TITLE
Integrate the tlog server in the nbdserver

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#40]
Only for boot and db disks

So the nbdserver does not only have to put the data to a storagecluster, it should also use the tlogclient to register all modified blocks there.

- [x] initial integration (prototyp-ish) (see: https://github.com/g8os/blockstor/commit/2cae45a47867e461a0c4a7206101870a7edc09e9);
- [ ] improved error handling;
- [ ] improved tlogserver (where needed);
- [x] massive performance improvement (currently it runs very slow, see 2cae45a);

**Comment by GlenDC** [comment]
https://github.com/g8os/blockstor/tree/tlog-integration-into-nbdserver is the (WIP) feature brach for this issue.

Issue https://github.com/g8os/gonbdserver/issues/3 is possibly related.

**Comment by iwanbk** [comment]
@GlenDC as we talked in telegram, please let me know the expected behavior of tlog client in case of error. I can help if needed.

**Comment by GlenDC** [comment]
@iwanbk I just finished the initial integration. You can find it on the same branch (have overwritten the original commit). For now there seem to be a lot of errors. So the next immediate steps will be:

- fix the errors that we seem to be triggering so easily (seems as if the tcp connections get unstable, after a while);
- make the tlogclient as error resiliant as is possible and sensible;

and than I haven't even started speaking about improving the speed, as it really slows down the nbdserver by factor of 10-20 :(

**Comment by iwanbk** [comment]
```
@iwanbk I just finished the initial integration. You can find it on the same branch (have overwritten the original commit)
```
I think you can merge it to master if it work, so we can split the improvements into different branches/issues
```
fix the errors that we seem to be triggering so easily (seems as if the tcp connections get unstable, after a while, see partial log below);
```
is it using the embedded ledisdb?
```
make the tlogclient as error resiliant as is possible and sensible
```
Some improvements i can think of:
- configurable write & read timeout
- re-create the conn automatically if closed


```
and than I haven't even started speaking about improving the speed, as it really slows down the nbdserver by factor of 10-20 :(
```
some speedup we can make:
- use the isa-l erasure code, it is certainly faster than the go lib
- make the C++ version compatible and use it, it also faster
- implement #106

**Comment by iwanbk** [comment]
@GlenDC how is the quick and easy way to test this? Both for correctness and perfomance

**Comment by GlenDC** [comment]
> I think you can merge it to master if it work, so we can split the improvements into different branches/issues

I think it would be best to keep it on a branch for now. If you want you can merge it into a new branch called `develop` or something, where we can work on shared features like this together. But I would like to keep it until `master`, until it runs a bit faster, and is working error-free in normal test runs.

> is it using the embedded ledisdb?

Yes

---

@iwanbk feel free to continue this work today, as I won't be working it anymore for the next 11-12 hours or so.

**Comment by GlenDC** [comment]
@iwanbk you can test it pretty easily, here is an example test flow:

1. Build nbdserver `cd nbdserver && go build`
2. Run nbdserver: `./nbdserver --address=":6666" --protocol="tcp" --export="myimg" -memorystorage`, you could also use unix sockets for faster performance
3. Convert an image: `qemu-img convert -n -O nbd myimg.img nbd+tcp://localhost:6666/myimg -p`

Than you could even run it using qemu, but that would only test if the nbdserver logic itself is valid, which we already know it is. So I guess after that you would be either inspecting the ardb via the redis client, or you would use some test script, or you would use your WIP cmd util.

The great thing about the nbdserver, is that you can run it entirely from 1 command line, without having to run another process. This does make it go much slower of course... but you know, it's great that there is the option.

**Comment by iwanbk** [comment]
```
But I would like to keep it until master, until it runs a bit faster, and is working error-free in normal test runs.
```
I do agree about error-free.

But not about runs faster because it is subjective.
I suggest to add option to disable/enable the tlog integration.

We shouldn't use the embedded ledisdb for this test for these reasons:
- it will blow up your RAM if we test it with a lot of data
- it is hard to verify from tlog decoder because ledisdb use random port
- we won't use it in production

**Comment by GlenDC** [comment]
> it will blow up your RAM if we test it with a lot of data

Yeah it's true, when having the tlogserver enabled, and having it all using the embedded ledisdb, we do go a bit crazy with 7+ of them :D

**Comment by GlenDC** [comment]
But for now I would like to keep it on a develop branch @iwanbk, as I don't think @robvanmieghem and @grimpy are done yet with testing and releasing of 1.1, so I would rather keep that master branch for 1.1 builds and hot fixes, until that release is behind us.

Does that sound OK for you @iwanbk?

**Comment by iwanbk** [comment]
```
Does that sound OK for you @iwanbk?
```
sure.
Please send PR or merge it by yourself when it is ready.

**Comment by GlenDC** [comment]
Also as I proposed on telegram:

> We might want to store the [local block content] offset alongside the LBA, in a sent transaction to the tlog server. This way we would be able to keep the content transactions unique to the new content. For now we are setting the entire content (new and old content already merged), which is inefficient, and it also gives a wrong impression of what happened in the history.

And for now I'm simply sending `nil`, when deleting content. Is this ok @iwanbk?

**Comment by GlenDC** [comment]
> Please send PR or merge it by yourself when it is ready.

You can now find the work rebased on https://github.com/g8os/blockstor/tree/develop, and I deleted the original feature branch, as that one is no longer needed.

**Comment by iwanbk** [comment]
```
And for now I'm simply sending nil, when deleting content. Is this ok @iwanbk?
```
yep

**Comment by iwanbk** [comment]
```
 For now there seem to be a lot of errors (triggered from the flusher code)
```
I can't reproduce the error using ardb.
And i'm afraid that embedded ledisdb is not my priority. Please let me know if we really need it.

**Comment by iwanbk** [comment]
```
And for now I'm simply sending nil, when deleting content. Is this ok @iwanbk?
```
After checking deeper, i think we can't do it because to replay it we need `length` variable for `WriteZeroesAt` func which is unknown for tlog.

some alternative solution:
- send the whole zeroed content to tlog, it is cleaner, and i think we rarely need to do this operation. So we don't really get performance penalty
- tlog send special value of length. Maybe negative or zero. And the backend handle it differently.

**Comment by iwanbk** [comment]
```
some speedup we can make:

use the isa-l erasure code, it is certainly faster than the go lib
```
while in the benchmark isa-l is 3x times faster, it doesn't give any performance boost when integrated into nbdserver.

**Comment by GlenDC** [comment]
Ok, let's go for:

- `send the whole zeroed content to tlog, it is cleaner, and i think we rarely need to do this operation. So we don't really get performance penalty`

I would rather not use a special value.

**Comment by robvanmieghem** [comment]
And doesn't the tlog server compresses it's content as well? Zeroed content will not take much storage there either.

**Comment by iwanbk** [comment]
Hi, what we should do in case of tlogserver failed? (it crashed, ardb crashed, etc...).

Because the aggregations form a kind of chain, means that it is useless if the chain broken in the middle.
Except the ndbserver have a kind of snapshot. Which make it able to be restored without need the tlog from beginning of the chain.

**Comment by iwanbk** [comment]
checked ` massive performance improvement` task because we don't have performance related task in this milestone.

**Comment by robvanmieghem** [comment]
> Because the aggregations form a kind of chain, means that it is useless if the chain broken in the middle.

@iwanbk Correct, if the tlog can not be reached, the io operation should fail. I think we should create a new issue for multicasting to more than 1 tlog server. Not for this iteration though.
