### ISSUE TITLE
Redis STUB type validation

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#45]
Currently we store normal, map (and soon set) values all in separate containers. This makes it that we can have a 3 different values, with the same key, while in a normal redis instance this would fail, complaining that we're trying to do an operation on a value of the wrong type.

How to reproduce:

```
SET FOO BAR
SADD FOO BAR 1
```

An error (`WRONGTYPE Operation against a key holding the wrong kind of value`) was expected.
However in our in-memory redis stub client, this will gladly succeed.

**Comment by robvanmieghem** [comment]
Will be fixed by https://github.com/g8os/blockstor/issues/46
