### ISSUE TITLE
Redis STUB Set support

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#47]
Add decent Set support to the Redis STUB,
PR https://github.com/g8os/blockstor/pull/44 adds super basic support for some SET operations,
but even those commands supported, are not completely correct.

`SADD` for example, should return `0` if the item already existed.
However because of the underlying implementation of these operations in the Redis STUB Client, it returns `1`, no matter if it already existed or not. None of our code relies on this feature, so it's not a big issue, but it might become an issue in the future.

**Comment by robvanmieghem** [comment]
Will be solved by https://github.com/g8os/blockstor/issues/46
