### ISSUE TITLE
tlog server implementation in go

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#49]
This would allow us to share some code between the tlog server and the nbdserver
like the pooling of the ardb's, failover mechanism, storagecluster configuration
...

the embedded ledisdb (on which Glen is working) for inmemory storage during development,...

and publishing the hashses to the rivine blockchain could import the required libraries directly from rivine without the need for reimplementation

since that is implemented in go as well

**Comment by iwanbk** [comment]
tasks list for working version that compatible with C++ version:
- [ ] compression with snappy
- [ ] erasure encoding
- [ ] aes cbc 256 bit encryption
- [ ] flush by size
- [ ] flush by timeout
- [ ] response to client

optimization:
- [ ] parallel flush
- [ ] use same redis library as nbdserver
- [ ] use go lib for erasure encoding
- [ ] use go lib for aes

**Comment by iwanbk** [comment]
i have added erasure encoding using templexxx/reedsolomon but disabled it again because it is too slow.

my benchmark
```GODEBUG=cgocheck=0 go test -bench=.                                                                                │-> seq= 168 . vol id = 31.1st 3 bytes=bca.
BenchmarkReedsolomonErasure16_4_4k-8              200000              7054 ns/op         580.62 MB/s               
BenchmarkReedsolomonErasure16_4_16k-8             100000             14552 ns/op        1125.86 MB/s               
BenchmarkIsalErasure16_4_4k-8                     500000              2286 ns/op        1791.40 MB/s               
BenchmarkIsalErasure16_4_16k-8                    200000              7004 ns/op        2339.01 MB/s    
```

16_4 there means K=16 and M=4 (K & M is erasure encoding variable)
4k means : 4K data
16K means : 16K data.

**Comment by robvanmieghem** [comment]
@iwanbk I noticed that in the templexxx implementation, you actually copy the data, in the isa-l you just reslice (which is a lot faster off course). Is there a specific reason for this?

**Comment by iwanbk** [comment]
my bad, the code is supposedly to be replaced with the optimised one

**Comment by iwanbk** [comment]
i've fixed the code and refactor it.
Surprisingly the difference become bigger

```
$ GODEBUG=cgocheck=0 go test -bench=.                                                                              │-> seq= 
BenchmarkReedsolomonErasure16_4_4k-8              300000              5056 ns/op         810.03 MB/s               
BenchmarkReedsolomonErasure16_4_16k-8             200000              9441 ns/op        1735.41 MB/s               
BenchmarkIsalErasure16_4_4k-8                    1000000              1157 ns/op        3537.36 MB/s               
BenchmarkIsalErasure16_4_16k-8                    500000              3268 ns/op        5012.35 MB/s 
```

**Comment by iwanbk** [comment]
Added 'string volume id' to the task list.
Initial code has been pushed to `tlog-string-volumeid ` branch.

At first, all seems OK, some aggregation field like name & size can be reconstructed back. But the blocks can't

**Comment by GlenDC** [comment]
Shouldn't that become 'vdisk id'?

**Comment by iwanbk** [comment]
Not sure about this. Because afaik it is only used in the code.

**Comment by GlenDC** [comment]
Yeah I don't know much about the tlog server, so perhaps you're dealing with a very different concept here. But otherwise I think also using vdisk from now on, would help in consistency. It's always a potential source of confusing when multiple words for the same concept are used in a single (umbrella) project.

**Comment by iwanbk** [comment]
I think you're right

**Comment by iwanbk** [comment]
i've implemented string volume id change.

I did a small benchmark with C++ version for 20K tlog messages.
C++ = 12 seconds
Go = 15 seconds. 
It seems similar to Nim version.

But proper benchmark should use multiple volumes because C++ version only use one core for each volume.

**Comment by iwanbk** [comment]
by comparing at templexxx & klauspost's API, i found that the API is quite different.
Maybe templexxx is based on old & less optimized klauspost's code.

@robvanmieghem if you want i can check it and make necessary improvement.

**Comment by iwanbk** [comment]
i think this sentence in the readme is enough explanation why templexxx library is not as fast as expected
```
It's not the fastest version here, if you want to get the fastest one, please send me email (I'm sorry for that, I wouldn't do this if I didn't have to):
```

**Comment by robvanmieghem** [comment]
> iwanbk
> @robvanmieghem if you want i can check it and make necessary improvement.
that would be good but let's focus on the functionality first

**Comment by robvanmieghem** [comment]
I made the isal dependency optional for erasure coding but it seems that the travis build is failing now:
https://github.com/g8os/blockstor/commit/17337f7d7be06447af8a8467a1176b138a18f0bd

**Comment by GlenDC** [comment]
Update from my feature branch (https://github.com/g8os/blockstor/tree/feat-replace-isal):

+ isa-l's aes is now only used when using the `isal` build flag;
+ by default the `crypto/aes` version (pure go) is used to encrypt in the flusher code;

Benchmark wise the Golang aes version seems to be doing way better, unless my benchmark code is flawed:

isal-aes ([flusher_isal.go#L36-L54](https://github.com/g8os/blockstor/blob/feat-replace-isal/tlogserver/flusher_isal.go#L36-L54)):

```
BenchmarkEncrypterEncrypt_4k_32k-2    	2000000000	         0.26 ns/op
BenchmarkEncrypterEncrypt_8k_32k-2    	       2	 509241361 ns/op
BenchmarkEncrypterEncrypt_4k_128k-2   	       1	1651387487 ns/op
BenchmarkEncrypterEncrypt_8k_128k-2   	       1	3182879190 ns/op
PASS
ok  	github.com/g8os/blockstor/tlogserver	15.498s
```

std-aes ([flusher_std.go#L25-L29](https://github.com/g8os/blockstor/blob/feat-replace-isal/tlogserver/flusher_std.go#L25-L29)):

```
testing: warning: no tests to run
BenchmarkEncrypterEncrypt_4k_32k-2    	2000000000	         0.02 ns/op
BenchmarkEncrypterEncrypt_8k_32k-2    	2000000000	         0.03 ns/op
BenchmarkEncrypterEncrypt_4k_128k-2   	2000000000	         0.08 ns/op
BenchmarkEncrypterEncrypt_8k_128k-2   	2000000000	         0.16 ns/op
PASS
ok  	github.com/g8os/blockstor/tlogserver	7.011s
```

Benchmark code can be found here: [flusher_test.go#L25-L48](https://github.com/g8os/blockstor/blob/feat-replace-isal/tlogserver/flusher_test.go#L25-L48)

**Comment by iwanbk** [comment]
```
by default the crypto/aes version (pure go) is used to encrypt in the flusher code;
```
except we changed our direction, we need to make sure that it is compatible with with C++ & Nim version.

to test it:
- run your Go tlog server
- send some tlog message using this example https://github.com/g8os/tlog/tree/master/client/examples
- get back the tlog data using this https://github.com/g8os/tlog/tree/go-data-decoder/tester/golastdata (it just written yesterday as part of https://github.com/g8os/tlog/issues/73, still has some issue but should work). for more reliable code, we can use https://github.com/g8os/tlog/tree/master/tester/get_last_data

**Comment by GlenDC** [comment]
Sure this feature branch is not yet finished, so with your feedback in mind @iwanbk, I'll ensure that the different versions are compatible with each other.

**Comment by iwanbk** [comment]
If possible, i think it is better to keep this branch compatible with C++ version
