### ISSUE TITLE
Remove Go 1.6 from travis build

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#55]
It failed in `tlogserver` branch but the failed part is not in tlogserver part.

```
vendor/github.com/gorilla/mux/context_gorilla.go:8:2: cannot find package "github.com/gorilla/context" in any of:
	/home/travis/gopath/src/github.com/g8os/blockstor/vendor/github.com/gorilla/context (vendor tree)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/github.com/gorilla/context (from $GOROOT)
	/home/travis/gopath/src/github.com/gorilla/context (from $GOPATH)
The command "go test $(go list ./... | grep -v vendor)" exited with 1.
1.79s$ ./scripts/codegeneration.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23031  100 23031    0     0   191k      0 --:--:-- --:--:-- --:--:--  192k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24508  100 24508    0     0   211k      0 --:--:-- --:--:-- --:--:--  211k
gridapi/generate.go:7: running "go-raml": exec: "go-raml": executable file not found in $PATH
2017/04/13 13:34:44 writing output: open private/cpuid.go: no such file or directory
exit status 1
tlogserver/vendor/github.com/klauspost/cpuid/generate.go:3: running "go": exit status 1
stat ../_codegen/main.go: no such file or directory
vendor/github.com/stretchr/testify/assert/forward_assertions.go:16: running "go": exit status 1
```

It is true that above failure is not strong enough reason to remove Go 1.6, but i think Go 1.6 is too old, not worth the time to fix it.

**Comment by GlenDC** [comment]
I agree. I'm ok with supporting only 1.7 and above. In fact, as this is still a project in development/progress, we could also just do 1.8 for now.

**Comment by GlenDC** [comment]
Godeps already has `1.7` as the registered Golang version in master (see: https://github.com/g8os/blockstor/blob/master/Godeps/Godeps.json#L3).

I work already from `1.8`, as I always upgrade as soon as the official release is launched.

Personally I think it's good enough to support the two last official versions, which in this case would be `1.7` and `1.8`. This would also mean that as soon as `1.9` is released, we would no longer support `1.7`.

**Comment by robvanmieghem** [comment]
I have no problem dropping 1.7 as well, core0 needs >=1.8 to build too.

**Comment by GlenDC** [comment]
@iwanbk once you rebase master in your branch, this issue should be gone for you.
