### ISSUE TITLE
create Lua scripts to be used as procedures in redis

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#6]

**Comment by robvanmieghem** [comment]
First needed script would be to create a new volume based on an existing one (copy of the metadata)

**Comment by robvanmieghem** [comment]
Jo De Boeck, [9 Mar 2017, 12:39]: 
`cat test.lua`
```
local source = ARGV[1]
local destination = ARGV[2]
local len = 0
local values
local value
local newkey

for _, key in pairs(redis.call('KEYS', source .. ':*')) do
    len = redis.call('LLEN', key)
    values = redis.call('LRANGE', key, 0, len)
    newkey = key:gsub(source, destination)
    redis.call("RESTORE", newkey, 0, redis.call("DUMP", key))
end
```
In python:
In [6]: scr = cl.register_script(open('test.lua').read())

In [7]: scr(keys=['source', 'destination'], args=['source', 'destination'])

**Comment by GlenDC** [comment]
I added the copyvolume as requested @robvanmieghem, and tested it in the following way:

1. connect to the `default` volume using `nbd-client`, make the file storage, and add some data, and disconnect again;
2. on the host (server) machine: create a new volume using the data from another volume (`default`): `redis-cli -p 16379 --eval luascripts/copyvolume.lua , default copy`;
3. connect to the `copy` volume using `nbd-client` (`-name copy`). Note that there is no need to make a file system, as we didn't start from fresh. Now read the files you made previously, you'll see they are there. Now modify some content, and unmount again;
4. connect to the `default` volume using `nbd-client`. You'll see that the files have not been altered, as the modifications happened on the `copy` volume, and not on the `default` volume;

@robvanmieghem, let me know if more scripts are needed, otherwise might be better to close this issue, and make a new issue in the future per (batch) of required scripts. So we don't clutter this issue for too long.

**Comment by robvanmieghem** [comment]
Closing this issue for now, let's define more more lua scripts later in functional bugs/features
