### ISSUE TITLE
tlogserver: replace isa-l with go AES and blake2

### ISSUE THREAD

**Issue by GlenDC** [g8os/blockstor#67]
Related to some tasks in #49

**Comment by iwanbk** [comment]
replacing blake2b should be straightforward as it is only on server.
But we need to check the compatibility with C++ & Nim version for the crypto

**Comment by GlenDC** [comment]
I might be wrong, but blake2b (replacing crc) will also involve the client, as the server checks the checksum of the payload, which will need to become a hash instead of an integer. Or am I missing something here?

**Comment by iwanbk** [comment]
```
but blake2b (replacing crc)
```
We use both now.
- blake2b : to hash the erasure encoded tlog aggregation 
- crc : tlog block checksum.

**Comment by iwanbk** [comment]
oh, i just realized that Go server already use Go blake2b lib.
Why we want to replace CRC with blake2b?

**Comment by GlenDC** [comment]
Was a suggestion by @robvanmieghem, he can probably go more into this. Unless I misunderstood him.

**Comment by GlenDC** [comment]
We could also imply use https://golang.org/pkg/hash/crc32/ for the pure-go version though

**Comment by iwanbk** [comment]
i tried that package, but it failed for me.
maybe you can try it again, maybe i did something wrong,

**Comment by GlenDC** [comment]
Working on it already @iwanbk, will let you know soon!

**Comment by iwanbk** [comment]
```
Was a suggestion by @robvanmieghem, he can probably go more into this. Unless I misunderstood him.
```
crc should be faster because it is less complex and should be enough to detect data error during transmission.

but hashing should be better for security.

**Comment by GlenDC** [comment]
ok yeah will need some work (if it is possible at all) to make the pure go version compatible with the CGO version...

CRC example:

```
crc of [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
3742692903 (isal)
3832490235 (hash/crc32)
```

AES example: 

``` 
cipher of [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

[48 27 6 41 19 251 97 154 181 131 92 207 241 2 122 145 158 175 23 149 82 196 199 89 1 152 43 136 211 9 158 1 94 167 62 129 64 160 8 74 169 81 157 189 230 237 35 78] (isal)
[123 148 103 158 82 100 191 132 6 156 104 100 51 7 239 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] (crypto/aes)
```

**Comment by iwanbk** [comment]
For AES, it is expected to be not compatible because the input of the func also different.
The go version doesn't have `initialization vector`.

For CRC, no idea why it is not compatible.

**Comment by GlenDC** [comment]
For CRC It's hopefully because the polynomial is different, working on a golang playground to try to get it to the same result, with the different code bases as reference

**Comment by GlenDC** [comment]
Ok turns out that the reason why my CRC is different between the pure go and cgo version is because [the used isa-l crc32 algo](https://github.com/01org/isa-l/blob/master/crc/crc_base.c#L138-L155) is different then [the hash/crc32 algo](https://github.com/golang/go/blob/master/src/hash/crc32/crc32_generic.go#L42-L48).

I ported the C isa-l algo to Golang, and use their poly, and then I do get the same crc as isa-l is returning us. Full playground can be found at: https://play.golang.org/p/CaUNre7E2e

That playground gives following output:

```
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
crc wanted: 3742692903 (source: isal-crc_ieee)
crc32.ChecksumIEEE(x): 3832490235
crc32.ChecksumIEEE(x, TABLE(crc32.IEEE)): 3832490235
crc32.ChecksumIEEE(x, TABLE(crc32.Castagnoli)): 1821626304
crc32.ChecksumIEEE(x, TABLE(crc32.Koopman)): 1205285842
crc32.ChecksumIEEE(x, TABLE(0x04C11DB7)): 4230742592
crc32_ieee_base(x): 3742692903
```

So that seems to work. Not sure where to go from here. While it is simple to now use the golang func (ported from isa-l C) in our code, it might not be the best idea to do so. I mean, I trust the Golang std hash code way more than some random code from an intel research group, but perhaps that's just me. Either way, if we want to make the pure go code compatible with the cgo code, for crc32 there is now a way...

Will continue tomorrow with this, and will then also check how I can make the aes code compatible.

**Comment by GlenDC** [comment]
@robvanmieghem what you think about all of this?

**Comment by GlenDC** [comment]
Good news. managed to get compatibility between the cgo and pure go crc code of the tlogserver. Apparently isa-l has [the function `crc32_iscsi`](https://github.com/01org/isa-l/blob/master/crc/crc_base_aliases.c#L34-L37) available, which as it turns out simply uses a table generated based on Castagnoli's polynomial `0x82f63b78` which can be found here https://godoc.org/hash/crc32#pkg-constants (and which has a better error detection rate then IEEE's polynomial).

There is only one gotcha... To make isal's crc algo compatible with the golang std version we require this patch applied on the (isa-l's) `crc32_iscsi` algo:

```diff
diff --git a/crc/crc_base.c b/crc/crc_base.c
index ee14f05..243c1a5 100644
--- a/crc/crc_base.c
+++ b/crc/crc_base.c
@@ -108,12 +108,12 @@ unsigned int crc32_iscsi_base(unsigned char *buffer, int len, unsigned int crc_i
 	p_buf = (unsigned char *)buffer;
 	unsigned char *p_end = buffer + len;
 
-	crc = crc_init;
+	crc = ~crc_init;
 
 	while (p_buf < (unsigned char *)p_end) {
 		crc = (crc >> 8) ^ crc32_table_iscsi_base[(crc & 0x000000FF) ^ *p_buf++];
 	}
-	return crc;
+	return ~crc;
 }
 
 // crc16_t10dif baseline function
```

It's a subtle change, but it means that the crc of `make([]byte, 42)` is `1821626304` (what go's `hash/crc32.Checksum` algo gives) and not `0` (which is what the current version of isa-l `crc32_iscsi_base` gives).

The crc tlogserver cgo- and go- code can therefore be compatible with each other, while only relying on the _modified_ isa-l (cgo) and _unmodified_ `hash/crc32` (go) code.

Going to see if the intel guys are willing to apply that patch, otherwise I need to either find another road, or we use a modified version of the isa-l lib algo (it's less than 20 lines, so easy enough to copy over) in our C++ code.

So that's a small step forward. Next up, AES :)

**Comment by GlenDC** [comment]
Good news on the CRC side. our crc go/cgo code is now fully compatible without required changes to isa-l, or the need for any custom algo implementations.

```go
import (
    "C"
    "unsafe"
)

func crcIsal(data []byte) (crc uint32) {
	crc = ^crc
	crc = uint32(C.crc32_iscsi(
		(*C.uchar)(unsafe.Pointer(&data[0])), // unsigned char *buffer
		(C.int)(len(data)),                   // int len
		C.uint(crc)))                         // unsigned int crc_init
	crc = ^crc
	return
}
```

and 

```go
import "hash/crc32"

var (
	castagnoliTable = crc32.MakeTable(crc32.Castagnoli)
)

func crcStd(data []byte) (crc uint32) {
	crc = crc32.Checksum(data, castagnoliTable)
	return
}
```

produce the same result, both using the `Castagnoli` polynomial. So with that I think the CRC part of this issue has been resolved. Final step is the AES part, which I'll start working on now.

**Comment by GlenDC** [comment]
The Go (default) version is now fully operational (afaik), using blake2b for hashing, and AES256+GCM for encryption. Tomorrow I'll work on making the C++ side work as well.

I replaced the `isal` build tag with the `cpp` build tag by the way, as it now also will rely on the `blake2` C library, not just the `isa-l` library.

**Comment by iwanbk** [comment]
```
Tomorrow I'll work on making the C++ side work as well.
```
i'll make it work, Michal will do the same for Nim version.

**Comment by GlenDC** [comment]
@iwanbk I meant implementing https://github.com/g8os/blockstor/blob/feat-replace-isal/tlog/crypto_cpp.go and finish implementing https://github.com/g8os/blockstor/blob/feat-replace-isal/tlog/hash_cpp.go

Or if you meant that, than feel free to finish that off in that branch, I wouldn't mind.

**Comment by iwanbk** [comment]
```
Or if you meant that, than feel free to finish that off in that branch, I wouldn't mind.
```
I meant in seastar side.
if pure Go already has good performance, i don't think you need to implement the cgo version.
We keep cgo and pure go version of erasure encoding because the pure Go version is too slow.

**Comment by GlenDC** [comment]
Implementing the cgo version has been dropped. The original feature branch will stay alive, such that a comparative benchmark can be done in the near future.

Benchmarks for the pure go algorithms on my dev machine (MacBook Pro (Retina, 13-inch, Early 2015)):

Encryption (AES256+GCM):

```
BenchmarkAES_4k_8k-4     	       2000000000	         0.02 ns/op	195438607.94 MB/s
BenchmarkAES_8k_8k-4     	       1000000000	         0.09 ns/op	93926596.43 MB/s
BenchmarkAES_4k_32k-4    	2000000000	         0.08 ns/op	48508694.29 MB/s
BenchmarkAES_8k_32k-4    	2000000000	         0.20 ns/op	40115641.07 MB/s
BenchmarkAES_4k_128k-4   	2000000000	         0.50 ns/op	8197959.86 MB/s
```

`BenchmarkAES_4k_8k` means, benchmark AES256+GCM encryption with packets of 4kb, `8*1024` times


Hashing (blake2b):

```
BenchmarkHash_4k_4k-4     	2000000000	         0.01 ns/op	412867391.25 MB/s
BenchmarkHash_16k_4k-4    	2000000000	         0.04 ns/op	414378325.97 MB/s
BenchmarkHash_4k_16k-4    	1000000000	         0.08 ns/op	49864645.37 MB/s
BenchmarkHash_16k_16k-4   	2000000000	         0.16 ns/op	103813926.87 MB/s
BenchmarkHash_4k_64k-4    	2000000000	         0.17 ns/op	24697752.14 MB/s
```

`BenchmarkHash_4k_4k` means, benchmark blake2b hashing with packets of 4kb, `4*1024` times

**Comment by robvanmieghem** [comment]
More than fast enough

**Comment by GlenDC** [comment]
Ok, in that case I'll delete the branch when I'm done with it.

**Comment by delandtj** [comment]
'more' gheghe

**Comment by GlenDC** [comment]
closed by PR #77

**Comment by robvanmieghem** [comment]
The updated benchmarks are indeed more in line of what can be expected.

**Comment by GlenDC** [comment]
@robvanmieghem but is it fast enough, or would you want to compare it with cgo benchmarks that @iwanbk can do on the [feat-replace-isal](https://github.com/g8os/blockstor/tree/feat-replace-isal) (throw-away) branch?

**Comment by robvanmieghem** [comment]
it's fast enough although I am a bit curious what cgo can do, it is not top priority

**Comment by GlenDC** [comment]
Could be interesting to find out for sure. I quite like C, its power and its simplicity. The only thing I don't like about it, is the dependency hell and poor tooling around you get with it. Especially when you need to have it working on many different platforms. So if speed becomes ever an issue, I do really believe that we can get the same speed with Rust. And with Rust you get the same easy cross compilation features as we're enjoying now with Golang. And as it also allows you to expose a C interface, it shouldn't be harder to use it with CGO than C is.
