### ISSUE TITLE
Tool to recreate a vdisk from the tlogs

### ISSUE THREAD

**Issue by robvanmieghem** [g8os/blockstor#86]

**Comment by iwanbk** [comment]
depend on #40

**Comment by iwanbk** [comment]
I can see two options to implement this:

(1) the tool work as nbd client
 it connects to nbdserver and replay the tlogs as nbd client
pros:
- simple, clean, and easy

cons:
- slower because of communication overhead between nbd server & client
- it seems we need to implement nbd client in Go first

(2) use `nbdserver.ardb.Backend.WriteAt` directly
as defined at https://github.com/g8os/blockstor/blob/3588ab4e349a5318e024b472362fd1e52b384b81/nbdserver/ardb/backend.go#L19

pros:
- faster

cons:
- this tool might need to know a lot about nbdserver internals especially the configurations

**Comment by iwanbk** [comment]
just found an ndb client library https://github.com/akmistry/go-nbd

**Comment by iwanbk** [comment]
```
just found an ndb client library https://github.com/akmistry/go-nbd
```
this lib doesn't support tcp & unix socket, i'm checking if we can improve it.

**Comment by robvanmieghem** [comment]
If we go this way, it would make the tool complex to run since you would need to start up a seperate nbdserver instance with the right configuration and write everything through the nbdclient.
I understand when using backend.WriteAt directly, it requires some more knowledge about the nbdserver internals but maybe we can create a simpler factorymethod for it so that it becomes just as easy to create such a backend as starting up an nbdserver with the same parameters would be.

**Comment by iwanbk** [comment]
```
If we go this way, it would make the tool complex to run since you would need to start up a seperate nbdserver instance with the right configuration and write everything through the nbdclient.
```
yes, i knew it.
and i thought that it makes things simpler because the user doesn't need to learn about this tool, he only need to knows how to configure nbd server.
But maybe i missed something here

```
I understand when using backend.WriteAt directly, it requires some more knowledge about the nbdserver internals but maybe we can create a simpler factorymethod for it so that it becomes just as easy to create such a backend as starting up an nbdserver with the same parameters would be.
```
ok, checking it.

**Comment by iwanbk** [comment]
it seems we already have the factory

**Comment by iwanbk** [comment]
I managed to create the backend, i'll see if we can make it simpler.

Still need to wait for #40.

From my quick check, the integration prototype at https://github.com/g8os/blockstor/tree/tlog-integration-into-nbdserver should work fine. will check it.

**Comment by GlenDC** [comment]
The integration prototype "works" kind-off at https://github.com/g8os/blockstor/tree/tlog-integration-into-nbdserver (although it is really not handling errors well at all), but even worse is that is really as slow as a handicap turtle

**Comment by iwanbk** [comment]
Working code, without delete operation, can be found in `tlogreplay` branch.

my tests:

(1) convert a lede image to qemu image and store it to nbdserver with tlogserver enabled

run nbdserver
```
./nbdserver --address=":6666" --protocol="tcp" --export="myimg"  -tlogrpc=127.0.0.1:11211 -testardbs=127.0.0.1:16377,127.0.0.1:16378
```
We store the data at `127.0.0.1:16378`

Run tlogserver
```
./tlogserver -objstor-addresses=127.0.0.1:16379 
```

convert the image to qemu image
```
qemu-img convert -n -O nbd ~/iso/lede-17.01.1-x86-64-combined-ext4.img nbd+tcp://localhost:6666/myimg -p
```

(2) make sure we can run the image
```
qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 -net nic -net user -drive file=nbd+tcp://localhost:6666/myimg,index=0,format=raw
```

(3) destroy the ardb

destroy ardb data

(4) make sure we can't run the image anymore
restart ndb server and run the image again

(5) run tlogreplay
```
./tlogreplay -vdiskid=myimg
```

(6) make sure we can run the image again
restart nbd server and run the image again.

i'm going to continue the work on the deletion part

**Comment by iwanbk** [comment]
I did another test
- use it as ext4 filesystem as described in https://github.com/g8os/blockstor/blob/cf69d65a3c16d73c75fc1d989fda0658b1fb0484/nbdserver/readme.md#test-locally
- copy 257 MB of lede image
- destroy the ardb data
- rebuild using tlogreplay
- compare the restored lede image with the original file using `cmp` command

test passed :)

**Comment by iwanbk** [comment]
the tool has been merged at #115.

I don't close the issue yet because i'm still thinking to add automatic test for this tool.

Because testing this tool manually, is error prone, sometimes i spend > 15 minutes for the test that could be done in < 5 mins

**Comment by iwanbk** [comment]
```
 i'm still thinking to add automatic test for this tool.
```
@GlenDC @robvanmieghem any idea to write some data to nbdserver and read it back that could be done in unit test?

**Comment by GlenDC** [comment]
If you use the embedded ledisdb servers, you can start the entire cluster in memory up, and write pretty much anything to the cluster. If it's a lot of data, I would simply generate a random buffer. If it's only a few blocks you could specify some static content. Also keep your blocks small, you can for example limit them to 8 bytes per block, no reason to go for 4KiB blocks.

So you could generate random data, which would be like an image. Write that data using the (deduped) backend (which should send it to tlog internally), then destroy the ardb data (you can cheat and create a utility function for this in the test file and delete that data manually). And then use your replay logic, and read all the data back, and compare the data with the orginal data.

It's not a unit test, but it's still OK to have it in a `_test.go` file IMHO.

If you need some inspiration (although you do really want a big piece of random data I think, rather than the static few content I use), you can check out the ardb module's `_test.go` code, should give you an idea.

**Comment by iwanbk** [comment]
> Write that data using the (deduped) backend (which should send it to tlog internally

do you mean using `backend.WriteAt`?

> . And then use your replay logic, and read all the data back

Is it mean we read it using tlog replay?

What i need is a way to write and read the data back, without involving tlog replay.
I need those to simulate these:
- write to file in a mounted nbd device
- read from file in a mounted ndb device

Test scenario i want to create:
- write data to nbdserver
- destroy the ardb or whatever storage we use
- rebuild the data using tlog replay
- read the data back from nbdserver, and compare it with original data.

let me know if it does't make sense

**Comment by GlenDC** [comment]
> Working code, without delete operation, can be found in tlogreplay branch. my tests: ...

@iwanbk can you please retry a manual test again with the new code, I was trying your 6-step manual test with latest master and it doesn't seem to work for me.

Also I'll look tonight or tomorrow into helping you with the automated test.

But please could you provide new detailed steps how one can test the `g8stor restore vdisk` command with manual detailed steps. Thanks!

**Comment by GlenDC** [comment]
> Working code, without delete operation, can be found in tlogreplay branch.

What do you mean with delete operation by the way? Or is that comment out of date by now?

**Comment by iwanbk** [comment]
```
But please could you provide new detailed steps how one can test the g8stor restore vdisk command with manual detailed steps. Thanks!
```
sure, i'll first check it with old `tlogreplay`, as i never used `g8stor restore` before, and in fact i just realized know about it's existence

**Comment by GlenDC** [comment]
I went through the commits I pushed (including the merge commits), and nothing critical has changed in the tlogserver and tlogreplay (now called `g8stor restore vdisk`). So it should just work AFAIK.

> sure, i'll first check it with old tlogreplay, as i never used g8stor restore before, and in fact i just realized know about it's existence

The old `tlogreplay` and the new `g8stor restore vdisk` are the same code.

**Comment by iwanbk** [comment]
i confirm that tlogreplay is not working anymore, i'm checking it..

**Comment by GlenDC** [comment]
Here is how I try to do the manual test of the `g8stor restore vdisk`:

1. Start 7 `redis-server` instances (I use my throw-away tool https://github.com/glendc/ardb for that, `ardb -n 7 -port 16379 -v`);
2. Start another redis-server (this time for (meta)dataStorage): `redis-server --port 6379`;
3. Start tlogserver: `tlogserver --objstor-addresses "localhost:16379" -v`
4. Start nbdserver: `nbdserver --address=":6666" --protocol="tcp" -tlogrpc localhost:11211 -v`;
5. Convert a small image: `qemu-img convert -n -O nbd myimg.img nbd+tcp://localhost:6666/myvdisk -p`;
6. Start the image: `qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 -net nic -net user -drive file=nbd+tcp://localhost:6666/myvdisk,index=0,format=raw` (and confirm image can indeed run fine);
7. Stop nbdserver and Stop (meta)dataStorage ardb;
8. Start redis-server again for (meta)dataStorage: `redis-server --port 6379`;
9. Start nbdserver: `nbdserver --address=":6666" --protocol="tcp" -tlogrpc localhost:11211 -v`;
10. confirm that image indeed doesn't run anymore: `qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 -net nic -net user -drive file=nbd+tcp://localhost:6666/myvdisk,index=0,format=raw`;
11. replay tlog: `g8stor restore vdisk myvdisk -v` (gives no error or weird logs);
12.start image again and notice how image still doesn't seem to be loading: `qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 -net nic -net user -drive file=nbd+tcp://localhost:6666/myvdisk,index=0,format=raw`;

:(

**Comment by GlenDC** [comment]
> i confirm that tlogreplay is not working anymore, i'm checking it..

The weird part is that none of the actual tlogserver/tlogclient/tlogintegration/tlogreplay code seems to have changed in a fundamental way...

**Comment by GlenDC** [comment]
@iwanbk found the issue! You didn't flush the backend ever after writing to it. Which means the LBA never got flushed, and thus the metadata was never stored in the actual external storage (ardb).

**Comment by iwanbk** [comment]
thanks, it works for me now. Wondering why it was work wthout `Flush`

**Comment by iwanbk** [comment]
> write data to nbdserver
> destroy the ardb or whatever storage we use
> rebuild the data using tlog replay
> read the data back from nbdserver, and compare it with original data.
> let me know if it does't make sense

just realized that i should think in `block of data` instead of file-like data.
I think i fully understand what to do now.

**Comment by GlenDC** [comment]
@iwanbk this issue is complete, no? The tlogreplay tool is implemented, and seems to be working. Surely it can now just keep evolving with the improvements, and changes made to the nbdserver and tlog code modules. But that will never change. However this issue's aim is to make the tlogreplay tool, and that is done. So could we close it?

**Comment by iwanbk** [comment]
Thanks a lot @GlenDC
