### ISSUE TITLE
tlog : use same redis package as nbdserver

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#92]

**Comment by GlenDC** [comment]
Already fixed in integration of tlogserver into nbdserver.

@iwanbk is https://github.com/g8os/blockstor/commit/94fe8592515f731d78b5a3eff365d3158b216827 what you mean?

If you want I can already merge that commit into tlogserver, as that is not really specific to my work on integrating tlog into the nbdserver.

**Comment by iwanbk** [comment]
sure

**Comment by GlenDC** [comment]
@iwanbk opened a PR, if that's what you had in mind, you can merge it in. Otherwise I guess you could amend changes to that PR and merge it in afterwards, as I'm going to bed now.

**Comment by iwanbk** [comment]
i merge that PR because that is a good PR and really helps for testing.

But this issue is about using 'https://github.com/g8os/blockstor/tree/master/nbdserver/ardb', instead of using redigo directly.

It is make sense to use that package for tlog?

**Comment by GlenDC** [comment]
I assume you are referring to using [RedisPool](https://github.com/g8os/blockstor/blob/master/nbdserver/ardb/redispool.go#L14-L77)?

Dunno if it makes sense to use tlog, will think about that today, but if it does make sense, we could improve it a bit (if needed), and move it to the root blockstor module, so we can share it.

**Comment by GlenDC** [comment]
@iwanbk I don't think sharing the redispool between nbdserver and tlogserver makes sense. We could copy the logic and adapt where needed, but both projects seem to want different things from what a redispool is supposed to be.

A big difference is for example the fact that tlogserver accesses the pools via an index (`int`), while nbdserver.ardb wants them per connection (`string`).

You could always refactor stuff to make them want similar things, but code sharing isn't always desired, as it could also lead to more static design.

So if you agree @iwanbk , I think we could close this issue.

**Comment by iwanbk** [comment]
```
A big difference is for example the fact that tlogserver accesses the pools via an index (int), while nbdserver.ardb wants them per connection (string).
```
it is no a big difference, we can easily convert int to string.

But i agree with your other points.

I thought the pool provide a kind of failover mechanism as mention in the comment https://github.com/g8os/blockstor/issues/49#issue-221191198.
